version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://usertest:psstest@db:5432/kanastra-bd
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  db:
    image: postgres
    environment:
      POSTGRES_DB: kanastra-bd
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: psstest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
